package io.github.aleris.plugins.tscfg

import tscfg.generators.TemplateGenerator
import tscfg.generators.TemplateOpts

class ConfigGenerator(val task: GenerateTscfgTask) {
  fun generate(configSource: ConfigSource): String {
    val templateOpts = TemplateOpts(task.configFileIndent.get(), "#")
    val templateGenerator = TemplateGenerator(templateOpts)
    val gradleTaskName = task.name
    val specFileName = configSource.configFile.name
    val originalSource = templateGenerator.generate(configSource.objectType)
    val source = "## Generated with `$gradleTaskName` Gradle task\n" +
        "## Do not edit this file manually, change spec in `$specFileName\n\n" +
        "$originalSource\n"
    return source
  }
}